services:
  postgres:
    image: 'postgres:latest'
    container_name: meandai
    environment:
      - 'POSTGRES_DB=meandai'
      - 'POSTGRES_PASSWORD=meandai'
      - 'POSTGRES_USER=meandai'
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # porta AMQP
      - "15672:15672"   # porta da interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest